#!/bin/bash

project_directory(){
    echo "${PROJ_PROJECTS_HOME}/${1}"
}

wait_for(){
    local i=1
    local spinner="/-\|"
    local displayed=""
    local stop=""

    trap 'stop="true"' INT

    while "$@"; do
        if [ "true" == "${stop}" ]; then
            break;
        fi
        if [ "true" == "${displayed}" ]; then
            printf "\b"
        fi
        printf "${spinner:i++%${#spinner}:1}"
        displayed="true"
        sleep 0.5
    done

    trap - INT

    if [ "true" == "${displayed}" ]; then
        printf "\b \b"
    fi
}
