#!/bin/bash

command_dir(){
    local PROJ_NAME="${1}"

    if [[ -n "${PROJ_NAME}" && "" != "${PROJ_NAME}" ]]; then
        local PROJ_DIR=$(project_directory "${PROJ_NAME}")

        if [ -d "${PROJ_DIR}" ]; then
            if [ -d "${PROJ_DIR}/.proj" ]; then
                printf "${PROJ_DIR}\n"
            else
                printf "The ${PROJ_NAME} project appears to be located at ${PROJ_DIR}, but is not currently tracked by proj.\n"
                return 66
            fi
        else
            printf "The ${PROJ_NAME} project doesn't exist in directory ${PROJ_DIR}.\n"
            return 65
        fi
    else
        local PROJECTS_DIR=$(get_config "" "proj.paths.projects" "")
        printf "${PROJECTS_DIR}\n"
    fi
}

command_dir_help(){
    printf "USAGE\n"
    printf "   ${PROGRAM_NAME} dir [<project_name>]\n"
    printf "\n"
    printf "DESCRIPTION\n"
    printf "   The 'dir' command can be used to output a project directory using the project's name.  If no project name is provided, the base project directory will be printed.\n"
}

command_dir_help_short(){
    printf "Displays a project's directory.\n"
}
