#!/bin/bash

command_dir(){
    local PROJ_NAME=${1}

    if [[ -n ${PROJ_NAME} && "" != ${PROJ_NAME} ]]; then
        local PROJ_DIR=$(project_directory ${PROJ_NAME})

        if [ -d ${PROJ_DIR} ]; then
            echo ${PROJ_DIR}
        else
            echo "The ${PROJ_NAME} project doesn't exist in directory ${PROJ_DIR}."
        fi
    else
        echo "A project name is required to show the project directory.  Use '${PROGRAM_NAME} help dir' for help with the dir command."
    fi
}

