#!/bin/bash

command_help(){
    if [ $# -ne 0 ]; then
        if [ $# -gt 1 ]; then
            printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        fi

        for COMMAND_NAME in "$@"; do
            command_${COMMAND_NAME}_help
            if [ $# -gt 1 ]; then
                printf '%*s' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
            fi
        done
    else
        local MAX_COMMAND_NAME_LENGTH=0
        for VALID_COMMAND in ${VALID_COMMANDS[@]}; do
            if [ "${#VALID_COMMAND}" -gt "${MAX_COMMAND_NAME_LENGTH}" ]; then
                MAX_COMMAND_NAME_LENGTH=${#VALID_COMMAND}
            fi
        done
        ((MAX_COMMAND_NAME_LENGTH+=3))

        printf "usage: ${PROGRAM_NAME} [-v] [help] <command> [<command>...] [<args>]\n"
        printf "\n"
        printf "Commands:\n"
        for VALID_COMMAND in ${VALID_COMMANDS[@]}; do
            printf "   %-${MAX_COMMAND_NAME_LENGTH}s $(command_${VALID_COMMAND}_help_short)\n" "${VALID_COMMAND}"
        done
        printf "\n"
        printf "Use '${PROGRAM_NAME} help <command> [<command>...]' for help with specific commands.\n"
        printf "\n"
    fi
}
