#!/bin/bash

command_list(){
    local PROJECTS_DIR=$(get_config "" "proj.paths.projects" "")
    find "${PROJECTS_DIR}" -mindepth 1 -maxdepth 1 -type d -exec test -d {}/.proj \; -exec basename {} \;
}

command_list_help(){
    printf "USAGE\n"
    printf "   ${PROGRAM_NAME} list\n"
    printf "\n"
    printf "DESCRIPTION\n"
    printf "   The 'list' command is used to list all projects that are currently being managed by proj.\n"
}

command_list_help_short(){
    printf "Lists projects currently managed by proj.\n"
}
