#!/bin/bash

command_list(){
    if [[ -n ${PROJ_PROJECTS_HOME} && "" != ${PROJ_PROJECTS_HOME} ]]; then
        find ${PROJ_PROJECTS_HOME} -mindepth 1 -maxdepth 1 -type d -exec test -d {}/.proj \; -printf '%f\n'
    else
        echo "The PROJ_PROJECTS_HOME environment variable is not set.  Please set this to your projects root directory to list projects."
        return 69
    fi
}

command_list_help(){
    echo "USAGE"
    echo "   ${PROGRAM_NAME} list"
    echo ""
    echo "DESCRIPTION"
    echo "   The 'list' command is used to list all projects under the PROJ_PROJECTS_HOME directory that are currently being managed by proj."
}

command_list_help_short(){
    echo "Lists projects currently managed by proj."
}
