#!/bin/bash

command_start(){
    local PROJ_NAME=${1}

    if [[ -n ${PROJ_NAME} && "" != ${PROJ_NAME} ]]; then
        local PROJ_DIR=$(project_directory ${PROJ_NAME})

        if [ -d ${PROJ_DIR} ]; then
            if [ -f ${PROJ_DIR}/.proj/bin/start ]; then
                ${PROJ_DIR}/.proj/bin/start
            else
                echo "The ${PROJ_NAME} project doesn't have a start script located at ${PROJ_DIR}/.proj/bin/start.  Unable to start ${PROJ_NAME}."
                return 80
            fi
        else
            echo "The ${PROJ_NAME} project doesn't exist in directory ${PROJ_DIR}.  Unable to start ${PROJ_NAME}."
            return 65
        fi
    else
        echo "A project name is required to start a project.  Use '${PROGRAM_NAME} help start' for help with the start command."
        return 64
    fi
}

command_start_help(){
    echo "USAGE"
    echo "   ${PROGRAM_NAME} start <project_name>"
    echo ""
    echo "DESCRIPTION"
    echo "   The 'start' command is used to start an existing project."
}

command_start_help_short(){
    echo "Starts a project using its start script."
}
