#!/bin/bash

command_status(){
    local PROJECTS_DIR=$(get_config "" "proj.paths.projects" "")
    local PROJECT_STATUS_WRITTEN="n"

    # Grab process information
    local PROCESS_INFO=`ps -e | grep quickstart`

    # Loop through each project directory
    while IFS=  read -r -d $'\0'; do
        local PROJ_DIR="${REPLY}"
        local PROJ_NAME=`basename "${PROJ_DIR}"`
        local PROJ_NAME_WRITTEN="n"

        # Loop through each AEM instance in the project
        if [ -d "${PROJ_DIR}/sites/aem" ]; then
            while IFS=  read -r -d $'\0'; do
                local INSTANCE_DIR="${REPLY}"
                local INSTANCE_NAME=`basename "${INSTANCE_DIR}"`
                local INSTANCE_PID=`cat "${INSTANCE_DIR}/crx-quickstart/conf/cq.pid"`

                local INSTANCE_PROCESS_STRING=`printf "${PROCESS_INFO}" | grep "${INSTANCE_PID}"`
                if [[ -n "${INSTANCE_PROCESS_STRING}" && "" != "${INSTANCE_PROCESS_STRING}" ]]; then
                    local RUNNING_PORT=`printf "${INSTANCE_PROCESS_STRING}" | grep -o "\-p\s[0-9]\+" | grep -o "[0-9]\+"`
                    local RUNNING_DEBUG_PORT=`printf "${INSTANCE_PROCESS_STRING}" | grep -o "\-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=[0-9]\+" | grep -o "[0-9]\+"`

                    if [ "n" == "${PROJ_NAME_WRITTEN}" ]; then
                        if [ "y" == "${PROJECT_STATUS_WRITTEN}" ]; then
                            printf "\n"
                        fi
                        printf "${PROJ_NAME}\n"
                        PROJ_NAME_WRITTEN="y"
                    fi

                    printf " \`- ${INSTANCE_NAME}\n"
                    printf "     \`- Port:       ${RUNNING_PORT}\n"
                    printf "     \`- Debug Port: ${RUNNING_DEBUG_PORT}\n"

                    PROJECT_STATUS_WRITTEN="y"
                fi
            done < <(find "${PROJ_DIR}/sites/aem" -mindepth 1 -maxdepth 1 -type d -exec test -f {}/crx-quickstart/conf/cq.pid \; -print0)
        fi
    done < <(find "${PROJECTS_DIR}" -mindepth 1 -maxdepth 1 -type d -exec test -d {}/.proj \; -print0)

    # Write no running projects message if nothing was written
    if [ "n" == "${PROJECT_STATUS_WRITTEN}" ]; then
        printf "No running projects.\n"
    fi
}

command_status_help(){
    printf "USAGE\n"
    printf "   ${PROGRAM_NAME} status\n"
    printf "\n"
    printf "DESCRIPTION\n"
    printf "   The 'status' command is used to display information about running AEM instances.  This is helpful when trying to determine which project is running AEM instances.\n"
}

command_status_help_short(){
    printf "Lists information about running AEM instances for each project.\n"
}
