#!/bin/bash

command_stop(){
    local PROJ_NAME=${1}
    shift

    AEM_INSTANCE_NAMES=(author)
    if [ $# -gt 0 ]; then
        AEM_INSTANCE_NAMES=("${@}")
    fi

    if [[ -n ${PROJ_NAME} && "" != ${PROJ_NAME} ]]; then
        local PROJ_DIR=$(project_directory ${PROJ_NAME})

        if [ -d ${PROJ_DIR} ]; then
            if [ -f ${PROJ_DIR}/.proj/bin/stop ]; then
                for AEM_INSTANCE_NAME in ${AEM_INSTANCE_NAMES[@]}; do
                    if [ -f ${PROJ_DIR}/sites/${AEM_INSTANCE_NAME}/crx-quickstart/bin/stop ]; then
                        echo "Stopping the ${AEM_INSTANCE_NAME} AEM instance"
                        ${PROJ_DIR}/.proj/bin/stop ${PROJ_DIR}/sites/${AEM_INSTANCE_NAME}/crx-quickstart/bin/stop
                    else
                        echo "The ${PROJ_NAME} project doesn't have the requested ${AEM_INSTANCE_NAME} AEM instance.  Unable to stop the ${AEM_INSTANCE_NAME} AEM instance."
                    fi

                    shift
                done
            else
                echo "The ${PROJ_NAME} project doesn't have a stop script located at ${PROJ_DIR}/.proj/bin/stop.  Unable to stop ${PROJ_NAME}."
                return 80
            fi
        else
            echo "The ${PROJ_NAME} project doesn't exist in directory ${PROJ_DIR}.  Unable to stop ${PROJ_NAME}."
            return 65
        fi
    else
        echo "A project name is required to stop a project.  Use '${PROGRAM_NAME} help stop' for help with the stop command."
        return 64
    fi
}

command_stop_help(){
    echo "USAGE"
    echo "   ${PROGRAM_NAME} stop <project_name> [<aem_instance>...]"
    echo ""
    echo "DESCRIPTION"
    echo "   The 'stop' command is used to stop an AEM instance for an existing project."
}

command_stop_help_short(){
    echo "Stops a project using its stop script."
}
